id: IB5F5F5AE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:00:28+00:00'
last_modified: '2022-06-08T08:31:33.779052+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD90010
  title: བརྒྱད་ཟིལ་རྫོང་གི་ལོ་རྒྱུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    04B5:
      image_group_id: I1PD90065
      title: ''
      total_pages: 574
      order: 1
      base_file: 04B5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
