id: P009087
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 19:22:15.068740
source_metadata:
  id: bdr:W1PD90010
  title: བརྒྱད་ཟིལ་རྫོང་གི་ལོ་རྒྱུས།
  author: ''
  volumes:
    b564ab055dd246fc93ceb24e74f21c37:
      image_group_id: I1PD90065
      title: ''
      volume_number: 1
      total_pages: 574
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
